### PR TITLE
[not ready] csvgoog command

### PR DESCRIPTION
**Pull request by sbma44**
I took a pass at https://github.com/onyxfish/csvkit/issues/48

I would love one or more additional sets of eyes on this!

Notes:
- `csvgoog --configure` to start a web-based authentication workflow
- repeated calls to `--configure` will result in invalid credentials unless you delete the app in your Google account's permissions dialog (they'll be missing a refresh token URL). This seems to be a PyDrive bug
- I'd like to do fuller testing, comparing spreadsheets' actual uploaded content, but this would either require a PyDrive patch or another dependency
- the presence of client_secrets.json and settings.yaml seems to be necessary despite PyDrive docs implying that tidier solutions are possible
- I wasn't able to get my tox environment working properly with python3 so while I have written with compatibility in mind, help evaluating py3 tests would be appreciated. 
- Credentials for a throwaway test account are included for testing; if you need the login information please let me know.

### CODE REVIEW

**Comment by sbma44** [comment]
Unfortunately it looks like python3 compatibility might currently be blocked by PyDrive:

https://github.com/googledrive/PyDrive/issues/26

That makes this a bigger quest. I will try to rework this with [gspread](https://github.com/burnash/gspread).

**Comment by pferate** [comment]
@sbma44, just so you know, I added Python 3 capability to PyDrive in my recent PR there.  Hopefully it will be merged in soon.

**Comment by sbma44** [comment]
@pferate awesome. I'll revist this once that's in.

**Comment by jpmckinney** [comment]
Hey @sbma44, as explained in https://github.com/onyxfish/csvkit/issues/48#issuecomment-174078441, I don't think this belongs in csvkit. If you can rework this as a generic command-line tool that let's you basically `cat` documents into Google Drive, that would be amazing! (and pipe-able from csvkit)

**Pull request closed without merging**
