### PR TITLE
Add failing tests, related #380

### PR DESCRIPTION
**Pull request by jpmckinney**
@onyxfish Does agate have anything like the `infers_type` kwarg?

### CODE REVIEW

**Comment by onyxfish** [comment]
It does not, but a functional equivalent, I think, would to specify Text as the type of every column:

[agate.Text()] * len(columns)

However this creates a chicken/egg problem if agate is what counts the columns, so this might require a change to agate to be done sanely. Lemme mull it over.

**Comment by onyxfish** [comment]
Assigned to myself so I don't forget to check it out.

**Comment by jpmckinney** [comment]
Adding link #380

**Comment by jpmckinney** [comment]
I tried passing `column_types=agate.TypeTester(limit=0)`, but that doesn't seem to do it.

**Comment by jpmckinney** [comment]
See https://github.com/onyxfish/agate/pull/450

**Pull request merged**
