### PR TITLE
Agate integration

### PR DESCRIPTION
**Pull request by jpmckinney**
Adding existing branch as PR.

### CODE REVIEW

**Comment by jpmckinney** [comment]
There's a single failure in test_table, which is fine because table is likely going away.

2.6 is failing because OrderedDict isn't available, but agate (which is 2.7+ only) uses it.

**Comment by jpmckinney** [comment]
Ok to drop support for 2.6?

**Comment by jpmckinney** [comment]
Fixes #477

**Comment by onyxfish** [comment]
Yes, 2.6 should still work, but we're not going to explicitly test it anymore. Py2.7 has been around for 5+ years at this point and several agate dependencies don't claim to support 2.6 anymore.

**Comment by onyxfish** [comment]
Also, to the extent there are clear priorities in the documentation and/or code, we should always be preferring Python3 at this point.

**Comment by jpmckinney** [comment]
K, dropping 2.6 from Travis. If 3.5 passes I'll merge (with that one exception).

Do you know off-hand how to skip a test? (Without just commenting it out / deleting it).

**Comment by jpmckinney** [comment]
Found `SkipTest`!

**Comment by onyxfish** [comment]
:+1:

**Pull request merged**
